export const IRREGULAR_VERBS = [
  {
    verb: 'answer',
    simplePast: 'answered',
    pastParticiple: 'answered',
    translate: 'responder',
  },
  {
    verb: 'add',
    simplePast: 'added',
    pastParticiple: 'added',
    translate: 'agregar',
  },
  {
    verb: 'apologise',
    simplePast: 'apologised',
    pastParticiple: 'apologised',
    translate: 'disculparse',
  },
  {
    verb: 'arrest',
    simplePast: 'arrested',
    pastParticiple: 'arrested',
    translate: 'arrestar',
  },
  {
    verb: 'arrive',
    simplePast: 'arrived',
    pastParticiple: 'arrived',
    translate: 'llegar',
  },
  {
    verb: 'ask',
    simplePast: 'asked',
    pastParticiple: 'asked',
    translate: 'preguntar',
  },
  {
    verb: 'attack',
    simplePast: 'attacked',
    pastParticiple: 'attacked',
    translate: 'atacar',
  },
  {
    verb: 'be',
    simplePast: 'was/were',
    pastParticiple: 'been',
    translate: 'ser o estar',
  },
  {
    verb: 'become',
    simplePast: 'became',
    pastParticiple: 'become',
    translate: 'convertirse',
  },
  {
    verb: 'begin',
    simplePast: 'began',
    pastParticiple: 'begun',
    translate: 'comenzar',
  },
  {
    verb: 'believe',
    simplePast: 'believed',
    pastParticiple: 'believed',
    translate: 'creer',
  },
  {
    verb: 'boil',
    simplePast: 'boiled',
    pastParticiple: 'boiled',
    translate: 'hervir',
  },
  {
    verb: 'book',
    simplePast: 'booked',
    pastParticiple: 'booked',
    translate: 'reservar',
  },
  {
    verb: 'borrow',
    simplePast: 'borrowed',
    pastParticiple: 'borrowed',
    translate: 'tomar prestado',
  },
  {
    verb: 'break',
    simplePast: 'broke',
    pastParticiple: 'broken',
    translate: 'romper',
  },
  {
    verb: 'bring',
    simplePast: 'brought',
    pastParticiple: 'brought',
    translate: 'traer',
  },
  {
    verb: 'build',
    simplePast: 'built',
    pastParticiple: 'built',
    translate: 'construir',
  },
  {
    verb: 'buy',
    simplePast: 'bought',
    pastParticiple: 'bought',
    translate: 'comprar',
  },
  {
    verb: 'carry',
    simplePast: 'carried',
    pastParticiple: 'carried',
    translate: 'llevar',
  },
  {
    verb: 'catch',
    simplePast: 'caught',
    pastParticiple: 'caught',
    translate: 'atrapar',
  },
  {
    verb: 'change',
    simplePast: 'changed',
    pastParticiple: 'changed',
    translate: 'cambiar',
  },
  {
    verb: 'chop',
    simplePast: 'chopped',
    pastParticiple: 'chopped',
    translate: 'picar',
  },
  {
    verb: 'clean',
    simplePast: 'cleaned',
    pastParticiple: 'cleaned',
    translate: 'limpiar',
  },
  {
    verb: 'climb',
    simplePast: 'climbed',
    pastParticiple: 'climbed',
    translate: 'escalar',
  },
  {
    verb: 'collect',
    simplePast: 'collected',
    pastParticiple: 'collected',
    translate: 'coleccionar',
  },
  {
    verb: 'come',
    simplePast: 'came',
    pastParticiple: 'come',
    translate: 'venir',
  },
  {
    verb: 'compose',
    simplePast: 'composed',
    pastParticiple: 'composed',
    translate: 'componer',
  },
  {
    verb: 'cook',
    simplePast: 'cooked',
    pastParticiple: 'cooked',
    translate: 'cocinar',
  },
  {
    verb: 'copy',
    simplePast: 'copied',
    pastParticiple: 'copied',
    translate: 'copiar',
  },
  {
    verb: 'cut',
    simplePast: 'cut',
    pastParticiple: 'cut',
    translate: 'cortar',
  },
  {
    verb: 'dance',
    simplePast: 'danced',
    pastParticiple: 'danced',
    translate: 'bailar',
  },
  {
    verb: 'describe',
    simplePast: 'described',
    pastParticiple: 'described',
    translate: 'describir',
  },
  {
    verb: 'destroy',
    simplePast: 'destroyed',
    pastParticiple: 'destroyed',
    translate: 'destruir',
  },
  {
    verb: 'die',
    simplePast: 'died',
    pastParticiple: 'died',
    translate: 'morir',
  },
  {
    verb: 'discover',
    simplePast: 'discovered',
    pastParticiple: 'discovered',
    translate: 'descubrir',
  },
  {
    verb: 'discuss',
    simplePast: 'discussed',
    pastParticiple: 'discussed',
    translate: 'discutir',
  },
  {
    verb: 'do',
    simplePast: 'did',
    pastParticiple: 'done',
    translate: 'hacer',
  },
  {
    verb: 'draw',
    simplePast: 'drew',
    pastParticiple: 'drawn',
    translate: 'dibujar',
  },
  {
    verb: 'dream',
    simplePast: 'dreamt/dreamed',
    pastParticiple: 'dreamt/dreamed',
    translate: 'soñar',
  },
  {
    verb: 'drink',
    simplePast: 'drank',
    pastParticiple: 'drunk',
    translate: 'beber',
  },
  {
    verb: 'drive',
    simplePast: 'drove',
    pastParticiple: 'driven',
    translate: 'conducir',
  },
  {
    verb: 'dye',
    simplePast: 'dyed',
    pastParticiple: 'dyed',
    translate: 'teñir',
  },
  {
    verb: 'eat',
    simplePast: 'ate',
    pastParticiple: 'eaten',
    translate: 'comer',
  },
  {
    verb: 'enjoy',
    simplePast: 'enjoyed',
    pastParticiple: 'enjoyed',
    translate: 'disfrutar',
  },
  {
    verb: 'explode',
    simplePast: 'exploded',
    pastParticiple: 'exploded',
    translate: 'explotar',
  },
  {
    verb: 'extinguish',
    simplePast: 'extinguished',
    pastParticiple: 'extinguished',
    translate: 'extinguirse',
  },
  {
    verb: 'fall',
    simplePast: 'fell',
    pastParticiple: 'fallen',
    translate: 'caer',
  },
  {
    verb: 'feed',
    simplePast: 'fed',
    pastParticiple: 'fed',
    translate: 'alimentar',
  },
  {
    verb: 'feel',
    simplePast: 'felt',
    pastParticiple: 'felt',
    translate: 'sentir',
  },
  {
    verb: 'fight',
    simplePast: 'fought',
    pastParticiple: 'fought',
    translate: 'pelear',
  },
  {
    verb: 'find',
    simplePast: 'found',
    pastParticiple: 'found',
    translate: 'encontrar',
  },
  {
    verb: 'fly',
    simplePast: 'flew',
    pastParticiple: 'flown',
    translate: 'volar',
  },
  {
    verb: 'forget',
    simplePast: 'forgot',
    pastParticiple: 'forgotten',
    translate: 'olvidar',
  },
  {
    verb: 'freeze',
    simplePast: 'froze',
    pastParticiple: 'frozen',
    translate: 'congelar',
  },
  {
    verb: 'fry',
    simplePast: 'fried',
    pastParticiple: 'fried',
    translate: 'freír',
  },
  {
    verb: 'give',
    simplePast: 'gave',
    pastParticiple: 'given',
    translate: 'dar',
  },
  {
    verb: 'go',
    simplePast: 'went',
    pastParticiple: 'gone',
    translate: 'ir',
  },
  {
    verb: 'grow',
    simplePast: 'grew',
    pastParticiple: 'grown',
    translate: 'crecer',
  },
  {
    verb: 'happen',
    simplePast: 'happened',
    pastParticiple: 'happened',
    translate: 'suceder',
  },
  {
    verb: 'hate',
    simplePast: 'hated',
    pastParticiple: 'hated',
    translate: 'odiar',
  },
  {
    verb: 'have',
    simplePast: 'had',
    pastParticiple: 'had',
    translate: 'tener',
  },
  {
    verb: 'hear',
    simplePast: 'heard',
    pastParticiple: 'heard',
    translate: 'oír',
  },
  {
    verb: 'help',
    simplePast: 'helped',
    pastParticiple: 'helped',
    translate: 'ayudar',
  },
  {
    verb: 'hire',
    simplePast: 'hired',
    pastParticiple: 'hired',
    translate: 'alquilar',
  },
  {
    verb: 'hope',
    simplePast: 'hoped',
    pastParticiple: 'hoped',
    translate: 'esperar',
  },
  {
    verb: 'hunt',
    simplePast: 'hunted',
    pastParticiple: 'hunted',
    translate: 'cazar',
  },
  {
    verb: 'hurt',
    simplePast: 'hurt',
    pastParticiple: 'hurt',
    translate: 'herir, doler',
  },
  {
    verb: 'imagine',
    simplePast: 'imagined',
    pastParticiple: 'imained',
    translate: 'imaginar',
  },
  {
    verb: 'invent',
    simplePast: 'invented',
    pastParticiple: 'invented',
    translate: 'inventar',
  },
  {
    verb: 'invite',
    simplePast: 'invited',
    pastParticiple: 'invited',
    translate: 'invitar',
  },
  {
    verb: 'jump',
    simplePast: 'jumped',
    pastParticiple: 'jumped',
    translate: 'saltar',
  },
  {
    verb: 'keep',
    simplePast: 'kept',
    pastParticiple: 'kept',
    translate: 'mantener, guardar',
  },
  {
    verb: 'kill',
    simplePast: 'killed',
    pastParticiple: 'killed',
    translate: 'matar',
  },
  {
    verb: 'know',
    simplePast: 'knew',
    pastParticiple: 'known',
    translate: 'saber',
  },
  {
    verb: 'leave',
    simplePast: 'left',
    pastParticiple: 'left',
    translate: 'salir, dejar',
  },
  {
    verb: 'lend',
    simplePast: 'lent',
    pastParticiple: 'lent',
    translate: 'prestar',
  },
  {
    verb: 'lie',
    simplePast: 'lied',
    pastParticiple: 'lied',
    translate: 'mentir',
  },
  {
    verb: 'lie',
    simplePast: 'lay',
    pastParticiple: 'lain',
    translate: 'yacer',
  },
  {
    verb: 'lift',
    simplePast: 'lifted',
    pastParticiple: 'lifted',
    translate: 'levantar',
  },
  {
    verb: 'like',
    simplePast: 'liked',
    pastParticiple: 'liked',
    translate: 'gustar',
  },
  {
    verb: 'listen',
    simplePast: 'listened',
    pastParticiple: 'listened',
    translate: 'escuchar',
  },
  {
    verb: 'live',
    simplePast: 'lived',
    pastParticiple: 'lived',
    translate: 'vivir',
  },
  {
    verb: 'look',
    simplePast: 'looked',
    pastParticiple: 'looked',
    translate: 'mirar',
  },
  {
    verb: 'lose',
    simplePast: 'lost',
    pastParticiple: 'lost',
    translate: 'perder',
  },
  {
    verb: 'love',
    simplePast: 'loved',
    pastParticiple: 'loved',
    translate: 'amar',
  },
  {
    verb: 'make',
    simplePast: 'made',
    pastParticiple: 'made',
    translate: 'hacer',
  },
  {
    verb: 'meet',
    simplePast: 'met',
    pastParticiple: 'met',
    translate: 'conocer, encontrar',
  },
  {
    verb: 'miss',
    simplePast: 'missed',
    pastParticiple: 'missed',
    translate: 'perder, extrañar',
  },
  {
    verb: 'offer',
    simplePast: 'offered',
    pastParticiple: 'offered',
    translate: 'ofrecer',
  },
  {
    verb: 'pack',
    simplePast: 'packed',
    pastParticiple: 'packed',
    translate: 'empaquetar',
  },
  {
    verb: 'pass',
    simplePast: 'passed',
    pastParticiple: 'passed',
    translate: 'pasar',
  },
  {
    verb: 'pay',
    simplePast: 'paid',
    pastParticiple: 'paid',
    translate: 'pagar',
  },
  {
    verb: 'peel',
    simplePast: 'peeled',
    pastParticiple: 'peeled',
    translate: 'pelar',
  },
  {
    verb: 'phone',
    simplePast: 'phoned',
    pastParticiple: 'phoned',
    translate: 'llamar por teléfono',
  },
  {
    verb: 'plan',
    simplePast: 'planned',
    pastParticiple: 'planned',
    translate: 'planificar',
  },
  {
    verb: 'play',
    simplePast: 'played',
    pastParticiple: 'played',
    translate: 'jugar',
  },
  {
    verb: 'pour',
    simplePast: 'poured',
    pastParticiple: 'poured',
    translate: 'verter',
  },
  {
    verb: 'prefer',
    simplePast: 'preferred',
    pastParticiple: 'preferred',
    translate: 'preferir',
  },
  {
    verb: 'prepare',
    simplePast: 'prepared',
    pastParticiple: 'prepared',
    translate: 'preparar',
  },
  {
    verb: 'push',
    simplePast: 'pushed',
    pastParticiple: 'pushed',
    translate: 'empujar',
  },
  {
    verb: 'rain',
    simplePast: 'rained',
    pastParticiple: 'rained',
    translate: 'llover',
  },
  {
    verb: 'read',
    simplePast: 'read',
    pastParticiple: 'read',
    translate: 'leer',
  },
  {
    verb: 'reduce',
    simplePast: 'reduced',
    pastParticiple: 'reduced',
    translate: 'reducir',
  },
  {
    verb: 'remember',
    simplePast: 'remembered',
    pastParticiple: 'remembered',
    translate: 'recordar',
  },
  {
    verb: 'rent',
    simplePast: 'rented',
    pastParticiple: 'rented',
    translate: 'alquilar',
  },
  {
    verb: 'rescue',
    simplePast: 'rescued',
    pastParticiple: 'rescued',
    translate: 'rescatar',
  },
  {
    verb: 'return',
    simplePast: 'returned',
    pastParticiple: 'returned',
    translate: 'volver, devolver',
  },
  {
    verb: 'ring',
    simplePast: 'rang',
    pastParticiple: 'rung',
    translate: 'llamar por teléfono',
  },
  {
    verb: 'run',
    simplePast: 'ran',
    pastParticiple: 'run',
    translate: 'correr',
  },
  {
    verb: 'save',
    simplePast: 'saved',
    pastParticiple: 'saved',
    translate: 'ahorrar, guardar',
  },
  {
    verb: 'say',
    simplePast: 'said',
    pastParticiple: 'said',
    translate: 'decir',
  },
  {
    verb: 'scream',
    simplePast: 'screamed',
    pastParticiple: 'screamed',
    translate: 'gritar',
  },
  {
    verb: 'search',
    simplePast: 'searched',
    pastParticiple: 'searched',
    translate: 'buscar',
  },
  {
    verb: 'see',
    simplePast: 'saw',
    pastParticiple: 'seen',
    translate: 'ver',
  },
  {
    verb: 'sell',
    simplePast: 'sold',
    pastParticiple: 'sold',
    translate: 'vendido',
  },
  {
    verb: 'send',
    simplePast: 'sent',
    pastParticiple: 'sent',
    translate: 'enviar',
  },
  {
    verb: 'shine',
    simplePast: 'shone',
    pastParticiple: 'shone',
    translate: 'brillar',
  },
  {
    verb: 'shoot',
    simplePast: 'shot',
    pastParticiple: 'shot',
    translate: 'disparar',
  },
  {
    verb: 'shut',
    simplePast: 'shut',
    pastParticiple: 'shut',
    translate: 'cerrar',
  },
  {
    verb: 'sing',
    simplePast: 'sang',
    pastParticiple: 'sung',
    translate: 'cantar',
  },
  {
    verb: 'sit',
    simplePast: 'sat',
    pastParticiple: 'sat',
    translate: 'sentarse',
  },
  {
    verb: 'skate',
    simplePast: 'skated',
    pastParticiple: 'skated',
    translate: 'patinar',
  },
  {
    verb: 'ski',
    simplePast: 'skied',
    pastParticiple: 'skied',
    translate: 'esquiar',
  },
  {
    verb: 'sleep',
    simplePast: 'slept',
    pastParticiple: 'slept',
    translate: 'dormir',
  },
  {
    verb: 'smell',
    simplePast: 'smelled',
    pastParticiple: 'smelled',
    translate: 'oler',
  },
  {
    verb: 'snore',
    simplePast: 'snored',
    pastParticiple: 'snored',
    translate: 'roncar',
  },
  {
    verb: 'speak',
    simplePast: 'spoke',
    pastParticiple: 'spoken',
    translate: 'hablar',
  },
  {
    verb: 'spend',
    simplePast: 'spent',
    pastParticiple: 'spent',
    translate: 'gastar',
  },
  {
    verb: 'start',
    simplePast: 'started',
    pastParticiple: 'started',
    translate: 'comenzar',
  },
  {
    verb: 'stay',
    simplePast: 'stayed',
    pastParticiple: 'stayed',
    translate: 'quedarse',
  },
  {
    verb: 'steal',
    simplePast: 'stole',
    pastParticiple: 'stolen',
    translate: 'robar',
  },
  {
    verb: 'stop',
    simplePast: 'stopped',
    pastParticiple: 'stopped',
    translate: 'detener',
  },
  {
    verb: 'study',
    simplePast: 'studied',
    pastParticiple: 'studied',
    translate: 'estudiar',
  },
  {
    verb: 'survive',
    simplePast: 'survived',
    pastParticiple: 'survived',
    translate: 'sobrevivir',
  },
  {
    verb: 'swim',
    simplePast: 'swam',
    pastParticiple: 'swum',
    translate: 'nadar',
  },
  {
    verb: 'take',
    simplePast: 'took',
    pastParticiple: 'taken',
    translate: 'tomar',
  },
  {
    verb: 'talk',
    simplePast: 'talked',
    pastParticiple: 'talked',
    translate: 'hablar',
  },
  {
    verb: 'teach',
    simplePast: 'taught',
    pastParticiple: 'taught',
    translate: 'enseñar',
  },
  {
    verb: 'tell',
    simplePast: 'told',
    pastParticiple: 'told',
    translate: 'decir',
  },
  {
    verb: 'thank',
    simplePast: 'thanked',
    pastParticiple: 'thanked',
    translate: 'agradecer',
  },
  {
    verb: 'think',
    simplePast: 'thought',
    pastParticiple: 'thought',
    translate: 'pensar',
  },
  {
    verb: 'throw',
    simplePast: 'threw',
    pastParticiple: 'thrown',
    translate: 'lanzar',
  },
  {
    verb: 'touch',
    simplePast: 'touched',
    pastParticiple: 'touched',
    translate: 'tocar',
  },
  {
    verb: 'try',
    simplePast: 'tried',
    pastParticiple: 'tried',
    translate: 'intentar',
  },
  {
    verb: 'understand',
    simplePast: 'understood',
    pastParticiple: 'understood',
    translate: 'entender',
  },
  {
    verb: 'use',
    simplePast: 'used',
    pastParticiple: 'used',
    translate: 'usar',
  },
  {
    verb: 'visit',
    simplePast: 'visited',
    pastParticiple: 'visited',
    translate: 'visitar',
  },
  {
    verb: 'wait',
    simplePast: 'waited',
    pastParticiple: 'waited',
    translate: 'esperar',
  },
  {
    verb: 'walk',
    simplePast: 'walked',
    pastParticiple: 'walked',
    translate: 'caminar',
  },
  {
    verb: 'want',
    simplePast: 'wanted',
    pastParticiple: 'wanted',
    translate: 'querer',
  },
  {
    verb: 'warn',
    simplePast: 'warned',
    pastParticiple: 'warned',
    translate: 'advertir',
  },
  {
    verb: 'wash',
    simplePast: 'washed',
    pastParticiple: 'washed',
    translate: 'lavar',
  },
  {
    verb: 'watch',
    simplePast: 'watched',
    pastParticiple: 'watched',
    translate: 'mirar',
  },
  {
    verb: 'wear',
    simplePast: 'wore',
    pastParticiple: 'worn',
    translate: 'llevar puesto',
  },
  {
    verb: 'win',
    simplePast: 'won',
    pastParticiple: 'won',
    translate: 'ganar',
  },
  {
    verb: 'work',
    simplePast: 'worked',
    pastParticiple: 'worked',
    translate: 'trabajar',
  },
  {
    verb: 'write',
    simplePast: 'wrote',
    pastParticiple: 'written',
    translate: 'escribir',
  },
];
